---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gce:podsecuritypolicy:elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gce:podsecuritypolicy:privileged
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  namespace: kube-system
