---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: guestbook
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: guestbook
  targetCPUUtilizationPercentage: 75
