---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    app: ingress-nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: metrics
    port: 10254
    targetPort: 10254
  selector:
    app: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  labels:
    k8s-app: nginx
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
